#!/bin/bash
# Unix Browser - Quick Command Reference

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║     Unix Browser - Installation & Build Commands            ║"
echo "║                     v1.0                                    ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "📦 INSTALLATION COMMANDS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  EASIEST: One-Click Installer (Batch)"
echo "   ↳ Right-click install.bat → Run as Administrator"
echo ""
echo "2️⃣  PowerShell Installer"
echo "   ↳ Right-click install.ps1 → Run with PowerShell"
echo ""
echo "3️⃣  Professional Installer (Inno Setup)"
echo "   ↳ Download Inno Setup from: https://jrsoftware.org/isdl.php"
echo "   ↳ Right-click installer.iss → Compile with Inno Setup"
echo "   ↳ Creates: dist/UnixBrowser-Setup.exe"
echo ""
echo "4️⃣  Interactive Menu"
echo "   ↳ Right-click menu.bat → Run as Administrator"
echo ""
echo ""
echo "💻 DEVELOPER COMMANDS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Build debug:"
echo "   dotnet build"
echo ""
echo "Build release (optimized):"
echo "   dotnet build -c Release"
echo ""
echo "Run the browser:"
echo "   dotnet run"
echo ""
echo "Publish for installation:"
echo "   dotnet publish -c Release --self-contained -o \"C:\Program Files\UnixBrowser\""
echo ""
echo ""
echo "📖 DOCUMENTATION:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Start here:"
echo "   • HOW_TO_INSTALL.md ........... Installation steps"
echo "   • QUICKSTART.md .............. Quick reference"
echo ""
echo "Full guides:"
echo "   • INSTALL.md ................. Detailed guide with troubleshooting"
echo "   • INSTALLATION_SYSTEM.md ..... Technical overview"
echo "   • INSTALLATION_COMPLETE.md ... System summary"
echo ""
echo "Reference:"
echo "   • README.md .................. Project overview"
echo "   • CONFIGURATION.md ........... Configuration options"
echo "   • PROJECT_SUMMARY.md ......... Architecture details"
echo ""
echo ""
echo "🎯 QUICK START:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "For End Users:"
echo "   1. Right-click install.bat"
echo "   2. Click 'Run as Administrator'"
echo "   3. Wait 1 minute"
echo "   4. Browser opens!"
echo ""
echo "For Developers:"
echo "   1. Open command prompt"
echo "   2. Run: dotnet run"
echo "   3. Browser opens!"
echo ""
echo ""
echo "✨ Features:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Multi-tab support (unlimited tabs)"
echo "✅ Favorites/bookmarks system"
echo "✅ PWA (Progressive Web App) support"
echo "✅ React Native web compatibility"
echo "✅ Terminal-style interface (black/green)"
echo "✅ Fast performance (Chromium engine)"
echo "✅ Self-contained executable"
echo "✅ Desktop & Start Menu shortcuts"
echo ""
echo ""
echo "🚀 Ready to go! Choose your installation method above."
